### PR TITLE
[net-misc/insync] revbump to improve wayland situation.

### PR DESCRIPTION
**Pull request by jkroonza**
In short:  avoid some QA issues and potential preserved-rebuild crap.

Signed-off-by: Jaco Kroon <jaco@uls.co.za>

### CODE REVIEW

**Comment by ppfeufer** [comment]
Thank you very much!

**Comment by jkroonza** [comment]
> Thank you very much!

My pleasure.  If we can "fix" the LICENSE we can potentially push this for ::gentoo ...

**Comment by ppfeufer** [comment]
> > Thank you very much!
> 
> My pleasure. If we can "fix" the LICENSE we can potentially push this for ::gentoo ...

Ya, the actual license is unknown to me, hence why `as-is`. I don't know which licenses `::gentoo` accepts, but maybe `EULA` would do the trick?

**Comment by ppfeufer** [comment]
There is also no license file packed with the `.deb` package ...

**Pull request merged**
